[package]
name = "get-tokens"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0", features = ["ws"] }
eyre = "0.6.12"
tokio = { version = "1.29.0", features = ["full"] }
